### ISSUE TITLE
브런치관리

### ISSUE THREAD

**Issue by ggamsang** [f-lab-edu/visualize_skyroad#5]
현재 테스트용 브런치를 머지(메인에)하였고,

develop브런치(위의 브런치를 기반으로)를 생성함.

이후 이슈/피알은 develop으로부터 새로 만들어서 진행 후 develop에 머지하며,

정기적으로 main에 머지하는 것으로.

**Comment by Ha-Young** [comment]
git flows 방식이네요

https://devocean.sk.com/blog/techBoardDetail.do?ID=165571&boardType=techBlog

**Comment by ggamsang** [comment]
git flows라고 했었죠, 이름을 잊고있어요 :) 위의 링크 확인하였습니다. 공유해주셔 감사합니당 :)
